[package]
name = "forcargo"
version = "0.1.0"
authors = ["harry <harry.ma@topnetwork.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
yastl = "0.1.2"
num_cpus = "1.10.1"
rayon = "1.0.0"

